### ISSUE TITLE
but what is about multivariate models for categorical variables ? 

### ISSUE THREAD

**Issue by Sandy4321** [luisroque/bayesian_time_series#1]
great code
but what is about multivariate models for categorical variables ?

**Comment by luisroque** [comment]
Hi @Sandy4321, for now I'll be focusing on continuous and discrete variables but not so much on categorical ones. We will start adding more variables in the future, but I also want to give some insights on how to extract the most knowledge that you can from the univariate representation of a time series, namely with non-linear models.
